<?php
/*
Plugin Name: Unfluff.io - Content Optimization
Plugin URI: https://unfluff.io/
Description: Unfluff your content for better readability and conversion.
Author: Unfluff.io
Author URI: https://unfluff.io/
Version: 1.0.1
*/

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

define('UNFLUFF_PATH', plugin_dir_path(__FILE__));
define('UNFLUFF_URL', plugin_dir_url(__FILE__));

function unfluff_metabox() {
    $screens = [ 'post', 'page' ];
    foreach ( $screens as $screen ) {
        add_meta_box(
            'unfluff_metabox',                 // Unique ID
            'Unfluff',      // Box title
            'unfluff_metabox_content',  // Content callback, must be of type callable
            $screen                            // Post type
        );
    }
}
add_action( 'add_meta_boxes', 'unfluff_metabox' );
function unfluff_metabox_content( $post ) {
    ?>
    <div id="unfluff-actions">
        <div id="unfluff-actions-top">
            <div class="gauge">
                <div class="percentage"></div>
                <div class="mask"></div>
                <img id="cat-img" src=" <?php echo plugin_dir_url( __FILE__ );?>assets/images/waiting.png">
            </div>
            <div class="unfluff-actions-buttons">
                <p id="unfluff-score" class="unfluff-score">Unfluff Score: <span id="unfluff-score-value">--</span></p>
                <p id="unfluff-check" class="unfluff-btn unfluff-check">Unfluff Check</p>
                <p id="unfluff-highlight-show" class="unfluff-btn highlight-show">Highlight All</p>
                <p id="unfluff-highlight-remove" class="unfluff-hide unfluff-btn highlight-remove">Remove Highlights</p>
                <p id="unfluff-info">0 = totally fluffy; 100 = no fluff</p>
            </div>
        </div>
    </div>
    <hr>
	<div id="fluff-sentences" class="fluff-sentences"></div>
    <div id="unfluff-announcement" class=" "></div>
    <?php
}

// check if block editor is used 
function unfluf_is_block_editor(){
    $current_screen = get_current_screen();
    return method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor();
}

// load unfluff js and css
function unfluff_enqueue_scripts($hook_suffix) {
	if( 'post.php' == $hook_suffix || 'post-new.php' == $hook_suffix ) {
        if( unfluf_is_block_editor() ) {
            wp_enqueue_script( 'unfluff', plugin_dir_url( __FILE__ ) . 'assets/js/block_editor.js', array( 'jquery' ), null, true );
        } else {
            wp_enqueue_script( 'unfluff', plugin_dir_url( __FILE__ ) . 'assets/js/classic_editor.js', array( 'jquery' ), null, true );
        }
	    wp_enqueue_style( 'unfluff', plugin_dir_url( __FILE__ ) . 'assets/css/admin_styles.css', array(), null );
        wp_localize_script( 'unfluff', 'unfluff_data',
            array( 
                'img_dir' => plugin_dir_url( __FILE__ ) . 'assets/images/',
                'email'   => get_option( 'unfluff_email' ),
                'license' => get_option( 'unfluff_license' )
            )
        );
   }
 }
 add_action( 'admin_enqueue_scripts', 'unfluff_enqueue_scripts', 9999 );



function unfluff_custom_editor_styles() {
	add_editor_style( plugin_dir_url( __FILE__ ) . 'assets/css/editor_styles.css', array(), null );
}
add_action('init', 'unfluff_custom_editor_styles');

// extend accepted html tags in TinyMCE
function unfluff_extend_tinyMCE_tags($initArray) {
    $extend = 'unfluffmark[id|class]';
    if ( isset( $initArray['extended_valid_elements'] ) ) {
        $initArray['extended_valid_elements'] .= ',' . $eextendxt;
    } else {
        $initArray['extended_valid_elements'] = $extend;
    }
    return $initArray;
}
add_filter('tiny_mce_before_init', 'unfluff_extend_tinyMCE_tags');


// Settings Page: Unfluff
// generated by https://wp-skills.com/tools/settings-options-page-generator
// Retrieving values: get_option( 'your_field_id' )
class Unfluff_Settings_Page {

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'unfluff_create_settings' ) );
		add_action( 'admin_init', array( $this, 'unfluff_setup_sections' ) );
		add_action( 'admin_init', array( $this, 'unfluff_setup_fields' ) );
	}

	public function unfluff_create_settings() {
		$page_title = 'Unfluff Settings';
		$menu_title = 'Unfluff';
		$capability = 'manage_options';
		$slug = 'unfluff';
		$callback = array($this, 'unfluff_settings_content');
        $icon = plugin_dir_url(__FILE__) . 'assets/images/icon.svg';
		$position = 70;
		add_menu_page($page_title, $menu_title, $capability, $slug, $callback, $icon, $position);
		
	}
    
	public function unfluff_settings_content() { ?>
		<div class="wrap">
			<h1>Unfluff Settings</h1>
            <p>Add your license key below. If you do not have one, visit <a href="https://unfluff.io">unfluff.io</a> to get one.</p>
			<?php settings_errors(); ?>
			<form method="POST" action="options.php" id="unluff_settings_form">
				<?php
					settings_fields( 'Unfluff' );
					do_settings_sections( 'Unfluff' );
					submit_button();
				?>
			</form>
            <div id="saveResult"></div>
            <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery('#unluff_settings_form').submit(function() { 
                    let email = jQuery('#unfluff_email').val();
                    let license = jQuery('#unfluff_license').val();
                    //console.log(email + ' and ' + license);
                    var settings = {
                        "url": "https://backend.unfluff.io/check",
                        "method": "POST",
                        "timeout": 0,
                        "headers": {
                            "Content-Type": "application/json"
                        },
                        "data": JSON.stringify({
                            "email": email,
                            "license": license
                        }),
                    };

                    jQuery.ajax(settings).done(function (response) {
                        //console.log(response.success);
                        if(response.success){
                            jQuery('#unluff_settings_form').ajaxSubmit({
                                success: function(){
                                    jQuery('#saveResult').html("<div id='saveMessage' class='successModal'></div>");
                                    jQuery('#saveMessage').append("<p><?php echo htmlentities(__('Settings Saved Successfully','wp'),ENT_QUOTES); ?></p>").show();
                                },
                                error: function(){
                                    jQuery('#saveResult').html("<div id='saveMessage' class='errorModal'></div>");
                                    jQuery('#saveMessage').append("<p><?php echo htmlentities(__('An error occured','wp'),ENT_QUOTES); ?></p>").show();
                                },
                                timeout: 5000
                            }); 
                         
                        } else{
                            jQuery('#saveResult').html("<div id='saveMessage' class='errorModal'></div>");
                            jQuery('#saveMessage').append("<p><?php echo htmlentities(__('We could not verify your email and license key!','wp'),ENT_QUOTES); ?></p>").show();
                        }
                        setTimeout("jQuery('#saveMessage').hide('slow');", 5000);
                    });

                    return false; // disable the default behavious or form submit (page relaod)
                    
                });
            });
            </script>
            <style>
                #saveMessage {
                    display: block;
                    position: fixed;
                    top: 50px;
                    right: 20px;
                    width: 300px;
                    height: auto;
                    padding: 5px 20px;
                    z-index:1002;
                    overflow: auto;
                    -moz-border-radius: 15px; 
                    -webkit-border-radius: 15px;
                    -moz-box-shadow: 5px 5px 10px #cfcfcf;
                    -webkit-box-shadow: 5px 5px 10px #cfcfcf;
                }
                .successModal {
                    border: 3px solid green;
                    background-color: #EFE;
                }
                .errorModal {
                    border: 3px solid red;
                    background-color: #ff7f7f;
                    color: #fff;
                }
            </style>
		</div> <?php
	}

	public function unfluff_setup_sections() {
		add_settings_section( 'Unfluff_section', '', array(), 'Unfluff' );
	}

	public function unfluff_setup_fields() {
		$fields = array(
                    array(
                        'section' => 'Unfluff_section',
                        'label' => 'Email address',
                        'placeholder' => 'cat@gmail.com',
                        'id' => 'unfluff_email',
                        'desc' => 'The email address associated with your license key',
                        'type' => 'email',
                    ),
        
                    array(
                        'section' => 'Unfluff_section',
                        'label' => 'License Key',
                        'placeholder' => 'xxx-xxxx-xxxx-xxxx',
                        'id' => 'unfluff_license',
                        'desc' => 'The license key you recieved from unfluff.io',
                        'type' => 'text',
                    )
		);
		foreach( $fields as $field ){
			add_settings_field( $field['id'], $field['label'], array( $this, 'unfluff_field_callback' ), 'Unfluff', $field['section'], $field );
			register_setting( 'Unfluff', $field['id'] );
		}
	}
	public function unfluff_field_callback( $field ) {
		$value = get_option( $field['id'] );
		$placeholder = '';
		if ( isset($field['placeholder']) ) {
			$placeholder = $field['placeholder'];
		}
		switch ( $field['type'] ) {
            
            
			default:
				printf( '<input name="%1$s" id="%1$s" type="%2$s" placeholder="%3$s" value="%4$s" />',
					$field['id'],
					$field['type'],
					$placeholder,
					$value
				);
		}
		if( isset($field['desc']) ) {
			if( $desc = $field['desc'] ) {
				printf( '<p class="description">%s </p>', $desc );
			}
		}
	}
    
}
new Unfluff_Settings_Page();

function unfluff_settings_scripts() {
    if ( is_admin() ){ // for Admin Dashboard Only
       // Embed the Script on our Plugin's Option Page Only
       if ( isset($_GET['page']) && $_GET['page'] == 'unfluff' ) {
          wp_enqueue_script('jquery');
          wp_enqueue_script( 'jquery-form' );
       }
    }
 }
 add_action( 'admin_init', 'unfluff_settings_scripts' );